#!/bin/sh

PATH=/usr/sbin:/usr/bin:/sbin:/bin
echo "Initialize utmp"
readonly utmp='/var/run/utmp'
if > "${utmp}" ; then
	chgrp utmp "${utmp}" || echo "Failed to chgrp ${utmp}"
	chmod 664  "${utmp}" || echo "Failed to chmod ${utmp}"
	return 0
else
	echo "Failed to truncate ${utmp}"
	return 1
fi
