#!/bin/sh
#
action=$1
service=$2

PATH=/sbin:/usr/sbin:/bin:/usr/bin

if [ -z ${service} ]
then
  echo "ERROR: service undefined"
  action="usage"
else
  if [ ! -d "/etc/svdir/${service}/supervise" ]
  then
    echo "ERROR: service ${service} not found"
    exit 1
  fi
fi

case "${action}" in
  up)
    /usr/bin/printf "u" >/etc/svdir/${service}/supervise/control
    /usr/bin/cat /etc/svdir/${service}/supervise/stat
    ;;
  down)
    /usr/bin/printf "d" >/etc/svdir/${service}/supervise/control
    /usr/bin/cat /etc/svdir/${service}/supervise/stat
    ;;
  status|st)
    /usr/bin/cat /etc/svdir/${service}/supervise/stat
    ;;
  enable)
    touch /etc/svdir/${service}/enable
    rm -f /etc/svdir/${service}/disable
    ;;
  disable)
    rm -f /etc/svdir/${service}/enable
    touch /etc/svdir/${service}/disable
    ;;
  *)
    echo "Usage: sv <down | up | status | enable | disable> service"
    ;;
esac
