#!/bin/sh
PATH=/sbin:/bin
EDITOR=vim
#cp interfaces /etc/network/
#ifdown wlan0
#ifup wlan0
apt update
apt upgrade
apt install -y vim
apt install -y git
apt install -y man
apt install -y make
apt install -y gcc
apt install -y sudo
apt install -y file
#cp gitconfig /home/pierre/.gitconfig
#cp git-credentials /home/pierre/.git-credentials
cd /home/pierre
git clone https://github.com/pyer/EeePC.git
chown -R pierre:pierre .
