#!/bin/sh -euC

# Disable service, if /dev/hvc{N} does not exist. See #914788.
if ! test -c /dev/hvc0 ; then
	rm /etc/runit/svdir/getty-hvc0
	exit 0
fi

pgrep -x getty -t hvc0 && exit 163
pgrep -x agetty -t hvc0 && exit 163
exec chpst -P getty 38400 hvc0 linux
