#!/bin/sh

. /lib/lsb/init-functions

[ -f /etc/default/rcS ] && . /etc/default/rcS
PATH=/bin:/usr/bin:/sbin:/usr/sbin
PROGRAM=/usr/bin/sensors

test -x $PROGRAM || exit 0
log_action_begin_msg "Setting sensors limits"
if [ "$VERBOSE" = "no" ]; then
	/usr/bin/sensors -s 1> /dev/null 2> /dev/null
	/usr/bin/sensors 1> /dev/null 2> /dev/null
else
	/usr/bin/sensors -s
	/usr/bin/sensors > /dev/null
fi
	