#!/bin/sh

[ -f /etc/default/console-setup ] && . /etc/default/console-setup

if [ "$CODESET" = "guess" ]; then
    case "$CHARMAP" in
        UTF-8)            CODESET=Uni2;;
        ISO-8859-1)       CODESET=Lat15 ;;
        ISO-8859-2)       CODESET=Lat2 ;;
        ISO-8859-3)       CODESET=Lat38 ;;
        ISO-8859-4)       CODESET=Lat7 ;; # sometimes Lat15
        ISO-8859-5)       CODESET=CyrSlav ;;
        ISO-8859-6)       CODESET=Arabic ;;
        ISO-8859-7)       CODESET=Greek ;;
        ISO-8859-8)       CODESET=Hebrew ;;
        ISO-8859-9)       CODESET=Lat15 ;;
        ISO-8859-10)      CODESET=Lat15 ;;
        ISO-8859-11)      CODESET=Thai ;;
        ISO-8859-13)      CODESET=Lat7 ;;
        ISO-8859-14)      CODESET=Lat38 ;;
        ISO-8859-15)      CODESET=Lat15 ;;
        ISO-8859-16)      CODESET=Lat2 ;;
        KOI8-R)           CODESET=CyrKoi ;;
        KOI8-U)           CODESET=CyrKoi ;;
        TIS-620)          CODESET=Thai ;;
        VISCII)           CODESET=Vietnamese ;;
        *)
            echo "Unsupported charmap $CHARMAP" >&2
            exit 1
            ;;
    esac
fi

echo "Setting up console font ${CODESET}-${FONTFACE}${FONTSIZE}"
font="/usr/share/consolefonts/${CODESET}-${FONTFACE}${FONTSIZE}.psf.gz"
if [ -f "$font" ]; then
    for tty in $ACTIVE_CONSOLES; do
        setfont -C $tty $font
    done
else
    echo "File $font not found" >&2
    exit 1
fi
