#!/bin/sh
# system one time tasks

PATH=/sbin:/usr/sbin:/bin:/usr/bin
INIT_VERBOSE="yes"

for script in /etc/runit/1.d/S* ; do
	"$script" start
done

# Now /run is mounted.
touch /run/runit.stopit
chmod 0 /run/runit.stopit

# That is it.  We do as little, as possible at stage1. Services, that do
# not have runscripts and invoked via init.d scripts are started at
# stage2. This way, daemon that hangs or otherwise misbehave do not
# block whole boot process.
#
# Thanks to Lornenz for suggestion.

# vim: ft=sh
/usr/bin/date -R >>/var/log/boot.log 
