#!/bin/sh
exec 2>&1

PATH=/sbin:/usr/sbin:/bin:/usr/bin
INIT_VERBOSE="yes"

echo 'Waiting for svdir services to stop ...'
for script in /etc/runit/svdir/* ; do
  echo -n "d" >$script/supervise/control
  echo -n "   - $script : "
  cat $script/supervise/stat
done

# Stop all runit-core sysv scripts
echo 'Killing other services in 3.d ...'
for script in /etc/runit/3.d/K* ; do
	"$script" stop
done

echo 'Shutdown...'
#sleep 20
