#!/bin/sh

PATH=/bin:/usr/bin
MSG="System is going down ..."

# echo 'disabled.' ; exit
#touch /run/runit.stopit
#chmod 100 /run/runit.stopit && echo "$MSG" | wall
#/bin/sleep 14
touch /run/runit.stopit
chmod 100 /run/runit.stopit
