#! /bin/sh
set -e

if [ -r /lib/cryptsetup/cryptdisks-functions ]; then
	. /lib/cryptsetup/cryptdisks-functions
else
	exit 0
fi

INITSTATE="remaining"
DEFAULT_LOUD="yes"

case "$CRYPTDISKS_ENABLE" in
[Nn]*)
	exit 0
	;;
esac

case "$1" in
start)
	do_start
	;;
stop)
	do_stop
	;;
esac
