#! /bin/sh
PATH=/sbin:/bin
# $1: Mount mode, to allow for remounting
MNTMODE="mount_noupdate"
[ "$1" = "reload" ] && MNTMODE="remount"

. /etc/mount-functions.sh

# Mount tmpfs on /run and/or /run/lock
mount_run  "$MNTMODE"
mount_lock "$MNTMODE"

# Mount proc filesystem on /proc
domount "$MNTMODE" proc "" /proc proc "-onodev,noexec,nosuid"
domount "$MNTMODE" securityfs "" /sys/kernel/security securityfs
domount "$MNTMODE" sysfs "" /sys sysfs "-onodev,noexec,nosuid"

if [ -d /sys/fs/pstore ]
then
  domount "$MNTMODE" pstore "" /sys/fs/pstore pstore ""
fi

# Mount efivarfs on /sys/firmware/efi/efivars if necessary
if [ -x /sys/firmware/efi ] && ! grep -sq ^efivarfs /proc/self/mounts; then
  # check efivarfs already mounted by kernel
  if ls /sys/firmware/efi/efivars/* 1>/dev/null 2>&1 || \
     ls /sys/firmware/efi/vars/* 1>/dev/null 2>&1; then
    return
  fi
  efivarsmnt=/sys/firmware/efi/efivars
  if [ -d $efivarsmnt ]; then
    # mount following mxlinux's efimount
    echo "Mounting efivarfs to $efivarsmnt"
    mount -t efivarfs efivarfs $efivarsmnt
  fi
fi
