#! /bin/sh
PATH=/sbin:/bin
# $1: Mount mode, to allow for remounting
MNTMODE="mount_noupdate"
[ "$1" = "reload" ] && MNTMODE="remount"
#
# This script gets called multiple times during boot, so must be idempotent.
#
TTYGRP=5
TTYMODE=620
[ -f /etc/default/devpts ] && . /etc/default/devpts

. /etc/mount-functions.sh

# idempotent, but does not change extant symlinks (or directories, for /dev/fd)
trylink() {
  test -h "/dev/$1" || test -d "/dev/$1" || ln -s -- "$2" "/dev/$1" || {
    echo "W: unable to ensure link /dev/$1 -> $2"
    ls -lad "/dev/$1"
  } >&2
}

# Ensure standard I/O nodes are present
trylink fd /proc/self/fd
trylink stdin  fd/0
trylink stdout fd/1
trylink stderr fd/2

# Mount a tmpfs on /run/shm
mount_shm "$MNTMODE"

# Mount /dev/pts
if [ ! -d /dev/pts ]
then
    mkdir --mode=755 /dev/pts
fi
domount "$MNTMODE" devpts "" /dev/pts devpts "-onoexec,nosuid,gid=$TTYGRP,mode=$TTYMODE"

