#!/bin/sh

ACTIVE_CONSOLES="/dev/tty[1-6]"

CHARMAP="UTF-8"
CODESET="Uni3"
FONTFACE="TerminusBold"
# FONTSIZE="22x11"
FONTSIZE="18x10"

echo "Setting up console font ${CODESET}-${FONTFACE}${FONTSIZE}"
font="/usr/share/fonts/psf/${CODESET}-${FONTFACE}${FONTSIZE}.psf.gz"
if [ -f "$font" ]; then
    for tty in $ACTIVE_CONSOLES; do
        setfont -C $tty $font
    done
else
    echo "File $font not found" >&2
    exit 1
fi
