#!/bin/sh
CHARMAP="UTF-8"
CODESET="Lat15"
FONTFACE="Fixed"
FONTSIZE="14"

echo "Setting up console font ${CODESET}-${FONTFACE}${FONTSIZE}"
font="/usr/share/consolefonts/${CODESET}-${FONTFACE}${FONTSIZE}.psf.gz"
if [ -f "$font" ]; then
    /bin/setfont $font
else
    echo "File $font not found" >&2
    exit 1
fi
