#!/bin/sh
# Include /usr/bin in path to find on_ac_power if /usr/ is on the root partition.
PATH=/usr/bin:/sbin:/bin
echo "Checking file systems"

fstab="/etc/fstab"
if [ -f "$fstab" ]; then
  while read DEV MTPT FSTYPE OPTS DUMP PASS
  do
      # find the real device
      case "$DEV" in
        ""|\#*)
          continue
        ;;
        /dev/*)
        ;;
        LABEL=*|UUID=*)
        DEV="$(findfs $DEV)"
        ;;
      esac
      case "$MTPT" in
        none)
          # skip swap partition
          continue
        ;;
        /)
          # check root fs
          if [ "$PASS" = "1" ]
          then
            if mount -n -o remount,ro $DEV $MTPT
            then
              # The actual checking is done here.
              # Only ext* file systems support `-f' option to fsck. See #686895
              fsck -C -p -T -t $FSTYPE $DEV
              # Remount root to final mode rw
              mount -n -o remount,$OPTS $DEV $MTPT
            else
              echo "ERROR: Cannot check root file system because it is not mounted read-only."
            fi
          fi
        ;;
        *)
          # check other fs
          if [ "$PASS" != "0" ]
          then
            if mountpoint -q "$MTPT"
            then
               mount -n -o remount,ro $DEV $MTPT
            fi
            fsck -C -p -T -t $FSTYPE $DEV
            mount -t $FSTYPE -o $OPTS $DEV $MTPT
          fi
        ;;
      esac
  done < "$fstab"
fi

# If possible, migrate /etc/mtab to be a symlink to /proc/mounts.
# Don't symlink if /proc/mounts does not exist.
if [ -r "/proc/mounts" ]; then
    rm -f "/etc/mtab"
    ln -fs "/proc/mounts" "/etc/mtab"
fi

# Make shm directory
[ -d /run/shm ] || mkdir --mode=755 /run/shm
