#! /bin/sh
# Include /usr/bin in path to find on_ac_power if /usr/ is on the root partition.
PATH=/usr/bin:/sbin:/bin
FSCK_LOGFILE=/var/log/fsck/checkfs

# Trap SIGINT so that we can handle user interupt of fsck.
trap "" INT

# Check the rest of the file systems.
echo "Checking file systems"
fsck -C -T -M -A -p
echo "Status: $?"
