#! /bin/sh
PATH=/sbin:/bin

# for ntfs-3g to get correct file name encoding
if [ -r /etc/default/locale ]; then
	. /etc/default/locale
	export LANG
fi

. /etc/mount-functions.sh

	#
	# Mount local file systems in /etc/fstab.
	#
  echo "Mounting local filesystems"
	if mountpoint -q /usr; then
			# May have been mounted read-only by initramfs.
			# Remount with unmodified options from /etc/fstab.
			mount -o remount /usr
	fi
	mount -a -t nonfs,nfs4,smbfs,cifs,ncp,ncpfs,coda,ocfs2,gfs,gfs2,ceph -O no_netdev

	# Instances of savelog(8), started from {checkroot} and {checkfs} will
	# wait for /var/log/fsck to appear to write logs there. If /var/log is
	# tmpfs, we have to make /var/log/fsck appear here. (see #524007)
	mkdir -p /var/log/fsck

	# Remount tmpfs filesystems; with increased VM after swapon,
	# the size limits may be adjusted.
	mount_run  mount_noupdate
	mount_lock mount_noupdate
	mount_shm  mount_noupdate

	# Now we have mounted everything, check whether we need to
	# mount a tmpfs on /tmp.  We can now also determine swap size
	# to factor this into our size limit.
	mount_tmp mount_noupdate

