#!/bin/sh -e
PATH=/sbin:/bin

[ -x /sbin/ifup ] || exit 0
[ -x /sbin/ifdown ] || exit 0

CONFIGURE_INTERFACES=yes
EXCLUDE_INTERFACES=
VERBOSE=no

[ -f /etc/default/networking ] && . /etc/default/networking

if [ "$CONFIGURE_INTERFACES" = no ]
then
  echo "Not configuring network interfaces, see /etc/default/networking"
  exit 0
fi

echo "Configuring network interfaces"
exclusions=""
for iface in $EXCLUDE_INTERFACES
do
  echo "Excluding $iface"
  exclusions="-X $iface $exclusions"
done

verbose=""
[ "$VERBOSE" = yes ] && verbose=-v

if [ -x /bin/udevadm ]; then
  /bin/udevadm settle
fi

echo "Configuring auto interfaces"
for iface in $(ifquery --list --allow=auto $exclusions)
do
  ifup $verbose $iface
done

echo "Configuring hotplug interfaces"
for iface in $(ifquery --list --allow=hotplug $exclusions)
do
  ifup $verbose $iface
done
