#!/bin/sh -e
PATH=/sbin:/bin
CONFIGURE_INTERFACES=yes

[ -x /sbin/ifup ] || exit 0
[ -x /sbin/ifdown ] || exit 0

if [ "$CONFIGURE_INTERFACES" = "no" ]
then
  echo "Configuring network interfaces is disabled"
  exit 0
fi

echo "Configuring network interfaces"

if [ -x /bin/udevadm ]; then
  /bin/udevadm settle
fi

for iface in $(ifquery --list --allow=auto)
do
  echo "  - $iface"
  ifup $iface
done

echo "Configuring hotplug interfaces"
for iface in $(ifquery --list --allow=hotplug)
do
  echo "  - $iface"
  ifup $iface
done
