#!/bin/sh -e
PATH=/sbin:/bin

CONFIGURE_INTERFACES=yes
EXCLUDE_INTERFACES=

[ -x /sbin/ifup ] || exit 0
[ -x /sbin/ifdown ] || exit 0

if [ "$CONFIGURE_INTERFACES" = "no" ]
then
  echo "Configuring network interfaces is disabled"
  exit 0
fi

echo "Configuring network interfaces"
exclusions=""
for iface in $EXCLUDE_INTERFACES
do
  echo "Excluding $iface"
  exclusions="-X $iface $exclusions"
done

if [ -x /bin/udevadm ]; then
  /bin/udevadm settle
fi

echo "Configuring auto interfaces"
for iface in $(ifquery --list --allow=auto $exclusions)
do
  ifup $iface
done

echo "Configuring hotplug interfaces"
for iface in $(ifquery --list --allow=hotplug $exclusions)
do
  ifup $iface
done
