#! /bin/sh
PATH="/sbin:/bin"

# Read through fstab line by line. If it is NFS, set the flag
# for mounting NFS file systems. If any NFS partition is found
# then wait around for it.
fstab="/etc/fstab"
waitnfs=
if [ -f "$fstab" ]; then
      while read DEV MTPT FSTYPE OPTS REST; do
        case "$DEV" in
          ""|\#*)
          continue
          ;;
        esac
        case "$OPTS" in
          noauto|*,noauto|noauto,*|*,noauto,*)
          continue
          ;;
        esac
        case "$FSTYPE" in
          nfs|nfs4|smbfs|cifs|coda|ncp|ncpfs|ceph)
          ;;
          *)
          continue
          ;;
        esac
        case "$MTPT" in
          /usr/local|/usr/local/*)
          ;;
          /usr|/usr/*)
          waitnfs="$waitnfs $MTPT"
          ;;
          /var|/var/*)
          waitnfs="$waitnfs $MTPT"
          ;;
        esac
      done < "$fstab"
fi

# Wait for each path, the timeout is for all of them as that's
# really the maximum time we have to wait anyway
TIMEOUT=900
for mountpt in $waitnfs; do
    echo "Waiting for $mountpt"

    while ! mountpoint -q $mountpt; do
      sleep 0.1

      TIMEOUT=$(( $TIMEOUT - 1 ))
      if [ $TIMEOUT -le 0 ]; then
        break
      fi
    done
done
