#!/bin/sh
echo "Initialize utmp"
utmp='/run/utmp'
if > "${utmp}" ; then
    /bin/chgrp utmp "${utmp}" || echo "Failed to chgrp ${utmp}"
    /bin/chmod 664  "${utmp}" || echo "Failed to chmod ${utmp}"
    return 0
else
    echo "Failed to truncate ${utmp}"
    return 1
fi
