#!/bin/sh
PATH=/sbin:/usr/sbin:/bin:/usr/bin

echo 'Waiting for services to stop'
for script in /etc/svdir/enabled/* ; do
  echo -n "d" >$script/supervise/control
done

WAIT=0
while [ $WAIT -eq 0 ]
do
  WAIT=1
  for script in /etc/svdir/enabled/* ; do
    echo -n "."
    if [ "$(cat $script/supervise/stat)" != "down" ]
    then
      WAIT=0
    fi
  done
done
echo ""

# Stop all with killer scripts
for script in /etc/shutdown.d/K* ; do
  "$script"
done
