#!/bin/sh
export PATH=/sbin:/bin

echo "Waiting for tasks to stop"
for task in /etc/tasks/enabled/*
do
  echo -n "d" >$task/control
done

WAIT=0
while [ $WAIT -eq 0 ]
do
  WAIT=1
  for task in /etc/tasks/enabled/*
  do
    echo -n "."
    if [ "$(cat $task/status)" != "down" ]
    then
      WAIT=0
    fi
  done
done
echo ""

echo "Shutdown in progress ..."
# Stop all with killer scripts
for script in /etc/shutdown.d/K*
do
  "$script"
done
