#!/bin/bash
#
# Variables
# ---------
# Config directory is usually "/etc/rotatelogs.d"
CONFIG=$1

# For cron
PATH=/bin:/sbin

# Functions
# ---------

usage() {
  echo "Version 1.0.0"
  echo
  echo "Usage: $0 <config directory>"
  exit 0
}

# Main
# ----
# Check argument
[ "$CONFIG" == "" ] && usage
[ "$CONFIG" == "help" ] && usage

# Check config dir
[ ! -d "$CONFIG" ] && echo "ERROR: $CONFIG is not a directory" && exit 1
[ ! -r "$CONFIG" ] && echo "ERROR: can't read $CONFIG" && exit 2

# Rotate logs defined in CONFIG
ln -s /etc/rotatelog "/sbin/-"
for file in ${CONFIG}/*
do
  $file
done
rm -f "/sbin/-"
exit 0
