#!/bin/sh -euC

# Disable service, if /dev/tty{N} does not exist. See #914788.
if ! test -c /dev/tty2 ; then
	rm /etc/svdir/getty-tty2
	exit 0
fi

pgrep -x getty -t tty2 && exit 163
pgrep -x agetty -t tty2 && exit 163
exec chpst -P getty 38400 tty2 linux
