#!/bin/sh
#
action=$1
service=$2

PATH=/sbin:/usr/sbin:/bin:/usr/bin

check_service() {
  if [ ! -d "/etc/svdir/${service}/supervise" ]
  then
    echo "ERROR: service ${service} not found"
    exit 1
  fi
}

case "${action}" in
  up)
    check_service
    /usr/bin/printf "u" >/etc/svdir/${service}/supervise/control
    /usr/bin/cat /etc/svdir/${service}/supervise/stat
    ;;
  down)
    check_service
    /usr/bin/printf "d" >/etc/svdir/${service}/supervise/control
    /usr/bin/cat /etc/svdir/${service}/supervise/stat
    ;;
  status|st)
    /usr/bin/cat /etc/svdir/${service}/supervise/stat
    ;;
  *)
    echo "Usage: sv [ down | up | status ] service"
    ;;
esac
