#!/bin/sh -euC

# Disable service, if /dev/tty{N} does not exist. See #914788.
if ! test -c /dev/tty4 ; then
	rm -rf /etc/svdir/tty4
	exit 0
fi

pgrep -x getty  -t tty4 && exit 163
pgrep -x agetty -t tty4 && exit 163
exec setsid getty 38400 tty4 linux
