#!/bin/sh -euC

# Disable service if /dev/tty{N} does not exist.
if ! test -c /dev/tty5
then
	/sbin/sv disable tty5
	exit 0
fi

# Log on /dev/tty{N}, automatic
exec setsid /sbin/logon /dev/tty5 pierre
