#!/bin/sh -euC

# Disable service, if /dev/tty{N} does not exist. See #914788.
if ! test -c /dev/tty3 ; then
	rm -rf /etc/svdir/tty3
	exit 0
fi

pgrep -x getty  -t tty3 && exit 163
pgrep -x agetty -t tty3 && exit 163
exec runsid getty 38400 tty3 linux
